name: RSS Feed Fetcher

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:       # Allows manual run

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS fetch script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python fetch_rss.py

      - name: Update README with latest articles
        run: python update_readme.py

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add articles.csv README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📌 Auto-update articles.csv & README.md"
            git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git HEAD:main
          fi
